export const ROLES = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
} as const

export const PERMISSIONS = {
  CLAIMS_CREATE_ALL: 'claims:create:all',
  CLAIMS_CREATE_CLIENT: 'claims:create:client',
  CLAIMS_CREATE_OWN: 'claims:create:own',
  CLAIMS_READ_ALL: 'claims:read:all',
  CLAIMS_READ_CLIENT: 'claims:read:client',
  CLAIMS_READ_OWN: 'claims:read:own',
  CLAIMS_UPDATE_ALL: 'claims:update:all',
  CLAIMS_UPDATE_CLIENT: 'claims:update:client',
  CLAIMS_UPDATE_OWN: 'claims:update:own',
  CLAIMS_TRANSITION_ALL: 'claims:transition:all',
  CLAIMS_TRANSITION_CLIENT: 'claims:transition:client',
  CLAIMS_TRANSITION_OWN: 'claims:transition:own',
  CLIENTS_CREATE_ALL: 'clients:create:all',
  CLIENTS_CREATE_CLIENT: 'clients:create:client',
  CLIENTS_READ_ALL: 'clients:read:all',
  CLIENTS_READ_CLIENT: 'clients:read:client',
  CLIENTS_READ_OWN: 'clients:read:own',
  CLIENTS_UPDATE_ALL: 'clients:update:all',
  CLIENTS_UPDATE_CLIENT: 'clients:update:client',
  INSURERS_CREATE_ALL: 'insurers:create:all',
  INSURERS_CREATE_CLIENT: 'insurers:create:client',
  INSURERS_CREATE_OWN: 'insurers:create:own',
  INSURERS_READ_ALL: 'insurers:read:all',
  INSURERS_READ_CLIENT: 'insurers:read:client',
  INSURERS_READ_OWN: 'insurers:read:own',
  INSURERS_UPDATE_ALL: 'insurers:update:all',
  INSURERS_UPDATE_CLIENT: 'insurers:update:client',
  INSURERS_UPDATE_OWN: 'insurers:update:own',
} as const

export const API_ROUTES = {
  health: '/health',
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me',
    verifyEmail: '/auth/verify-email',
    resendVerification: '/auth/resend-verification',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    changePassword: '/auth/change-password',
  },
  claims: {
    create: '/claims',
    list: '/claims',
    lookupClients: '/claims/lookup/clients',
    lookupClientAffiliates: '/claims/lookup/clients/:clientId/affiliates',
    lookupAffiliatePatients: '/claims/lookup/affiliates/:affiliateId/patients',
    lookupClientPolicies: '/claims/lookup/clients/:clientId/policies',
    history: '/claims/:id/history',
    timeline: '/claims/:id/timeline',
    invoices: '/claims/:id/invoices',
    invoiceById: '/claims/:id/invoices/:invoiceId',
    update: '/claims/:id',
    delete: '/claims/:id',
    getById: '/claims/:id',
    transition: '/claims/:id/transition',
  },
  clients: {
    create: '/clients',
    list: '/clients',
    getById: '/clients/:id',
    update: '/clients/:id',
    delete: '/clients/:id',
    timeline: '/clients/:id/timeline',
    policies: '/clients/:id/policies',
  },
  insurers: {
    create: '/insurers',
    list: '/insurers',
    getById: '/insurers/:id',
    update: '/insurers/:id',
    delete: '/insurers/:id',
    timeline: '/insurers/:id/timeline',
  },
} as const

export const ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  CONFLICT: 'CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  CLIENT_ERROR: 'CLIENT_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_SESSION_INVALID: 'AUTH_SESSION_INVALID',
  AUTH_ACCOUNT_DEACTIVATED: 'AUTH_ACCOUNT_DEACTIVATED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_CURRENT_PASSWORD_INCORRECT: 'AUTH_CURRENT_PASSWORD_INCORRECT',
  AUTH_VERIFICATION_TOKEN_INVALID: 'AUTH_VERIFICATION_TOKEN_INVALID',
  AUTH_RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',
  AUTH_IDENTITY_UNAVAILABLE: 'AUTH_IDENTITY_UNAVAILABLE',
  AUTH_INVALID_ORGANIZATION_NAME: 'AUTH_INVALID_ORGANIZATION_NAME',
  CLAIMS_CLIENT_NOT_FOUND: 'CLAIMS_CLIENT_NOT_FOUND',
  CLAIMS_CLIENT_INACTIVE: 'CLAIMS_CLIENT_INACTIVE',
  CLAIMS_AFFILIATE_NOT_FOUND: 'CLAIMS_AFFILIATE_NOT_FOUND',
  CLAIMS_AFFILIATE_INACTIVE: 'CLAIMS_AFFILIATE_INACTIVE',
  CLAIMS_AFFILIATE_CLIENT_MISMATCH: 'CLAIMS_AFFILIATE_CLIENT_MISMATCH',
  CLAIMS_PATIENT_NOT_FOUND: 'CLAIMS_PATIENT_NOT_FOUND',
  CLAIMS_PATIENT_INACTIVE: 'CLAIMS_PATIENT_INACTIVE',
  CLAIMS_PATIENT_CLIENT_MISMATCH: 'CLAIMS_PATIENT_CLIENT_MISMATCH',
  CLAIMS_CLAIM_NOT_FOUND: 'CLAIMS_CLAIM_NOT_FOUND',
  CLAIMS_PATIENT_NOT_DEPENDENT: 'CLAIMS_PATIENT_NOT_DEPENDENT',
  CLAIMS_FIELD_NOT_EDITABLE: 'CLAIMS_FIELD_NOT_EDITABLE',
  CLAIMS_POLICY_NOT_FOUND: 'CLAIMS_POLICY_NOT_FOUND',
  CLAIMS_POLICY_CLIENT_MISMATCH: 'CLAIMS_POLICY_CLIENT_MISMATCH',
  CLAIMS_INVOICE_NOT_FOUND: 'CLAIMS_INVOICE_NOT_FOUND',
  CLAIMS_INVALID_TRANSITION: 'CLAIMS_INVALID_TRANSITION',
  CLAIMS_INVARIANT_VIOLATION: 'CLAIMS_INVARIANT_VIOLATION',
  CLAIMS_REASON_REQUIRED: 'CLAIMS_REASON_REQUIRED',
  CLIENTS_CLIENT_NOT_FOUND: 'CLIENTS_CLIENT_NOT_FOUND',
  INSURERS_INSURER_NOT_FOUND: 'INSURERS_INSURER_NOT_FOUND',
  INSURERS_NAME_UNAVAILABLE: 'INSURERS_NAME_UNAVAILABLE',
  INSURERS_CODE_UNAVAILABLE: 'INSURERS_CODE_UNAVAILABLE',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

export * from './claims.js'
