export const ROLES = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
} as const

export const PERMISSIONS = {
  CLAIMS_CREATE_ALL: 'claims:create:all',
  CLAIMS_CREATE_CLIENT: 'claims:create:client',
  CLAIMS_CREATE_OWN: 'claims:create:own',
} as const

export const API_ROUTES = {
  health: '/health',
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me',
    verifyEmail: '/auth/verify-email',
    resendVerification: '/auth/resend-verification',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    changePassword: '/auth/change-password',
  },
  claims: {
    create: '/claims',
  },
} as const

export const ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  CONFLICT: 'CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  CLIENT_ERROR: 'CLIENT_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_SESSION_INVALID: 'AUTH_SESSION_INVALID',
  AUTH_ACCOUNT_DEACTIVATED: 'AUTH_ACCOUNT_DEACTIVATED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_CURRENT_PASSWORD_INCORRECT: 'AUTH_CURRENT_PASSWORD_INCORRECT',
  AUTH_VERIFICATION_TOKEN_INVALID: 'AUTH_VERIFICATION_TOKEN_INVALID',
  AUTH_RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',
  AUTH_IDENTITY_UNAVAILABLE: 'AUTH_IDENTITY_UNAVAILABLE',
  AUTH_INVALID_ORGANIZATION_NAME: 'AUTH_INVALID_ORGANIZATION_NAME',
  CLAIMS_CLIENT_NOT_FOUND: 'CLAIMS_CLIENT_NOT_FOUND',
  CLAIMS_CLIENT_INACTIVE: 'CLAIMS_CLIENT_INACTIVE',
  CLAIMS_AFFILIATE_NOT_FOUND: 'CLAIMS_AFFILIATE_NOT_FOUND',
  CLAIMS_AFFILIATE_INACTIVE: 'CLAIMS_AFFILIATE_INACTIVE',
  CLAIMS_AFFILIATE_CLIENT_MISMATCH: 'CLAIMS_AFFILIATE_CLIENT_MISMATCH',
  CLAIMS_PATIENT_NOT_FOUND: 'CLAIMS_PATIENT_NOT_FOUND',
  CLAIMS_PATIENT_INACTIVE: 'CLAIMS_PATIENT_INACTIVE',
  CLAIMS_PATIENT_CLIENT_MISMATCH: 'CLAIMS_PATIENT_CLIENT_MISMATCH',
  CLAIMS_PATIENT_NOT_DEPENDENT: 'CLAIMS_PATIENT_NOT_DEPENDENT',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
